services:
  - type: web
    name: workwithme-backend
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
    autoDeploy: true
